-- Quiz 1

-- 1. Create table SALARIES

CREATE TABLE SALARIES
(
    ID NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER NOT NULL,
    PROJECT_ID NUMBER NOT NULL,
    SALARY DECIMAL (10,2) NOT NULL,
    
    CHECK (SALARY > 500),
    
	CONSTRAINT SALARIES_PK PRIMARY KEY (ID)
    --CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
    --CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);

-- Create table PROJECTS

CREATE TABLE PROJECTS
(
    ID NUMBER NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    MANAGER_ID NUMBER NOT NULL,
    BUDGET DECIMAL (10,2) NOT NULL,
    DATE_OF_BEGINNING DATE NOT NULL,
    DATE_OF_ENDING DATE NOT NULL,
    
    
	CONSTRAINT PROJECTS_PK PRIMARY KEY (ID)
    --CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
    --CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);

-- Create table EMPLOYEES
CREATE TABLE EMPLOYEES
(
    ID NUMBER NOT NULL,
    MANAGER_ID NUMBER NOT NULL,
    DATE_OF_JOINING DATE NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    
    
	CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID)
    --CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
    --CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);

-- Add foreign keys to SALARIES
ALTER TABLE SALARIES ADD CONSTRAINT FK_SALARY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID);
ALTER TABLE SALARIES ADD CONSTRAINT FK_SALARY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID);
 
 --Add foreign key to PROJECTS
 
 ALTER TABLE PROJECTS ADD CONSTRAINT FK_MANAGER_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID);

--Add foreign key to EMPLOYEES

 ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID);
 
 ALTER TABLE EMPLOYEES MODIFY
 MANAGER_ID NUMBER NULL;
 
 DELETE FROM EMPLOYEES;
 
  ALTER TABLE PROJECTS MODIFY
 MANAGER_ID NUMBER NULL;

-- Count employees

SELECT COUNT(*) "Total"
FROM EMPLOYEES
INNER JOIN PROJECTS
ON EMPLOYEES.ID = PROJECTS.MANAGER_ID
WHERE PROJECTS.CODE = TO_CHAR('44905736599');

--
SELECT EMPLOYEES.FULL_NAME
FROM EMPLOYEES 
INNER JOIN SALARIES
ON EMPLOYEES.ID = SALARIES.EMPLOYEE_ID
WHERE SALARIES.SALARY >= 1000
AND SALARIES.SALARY <= 2500;








